def RED():
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a
    a if a else a

